---
title: "POKEMON"
author: "me:))"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(forcats)
library(fmsb)
library(dplyr)
library(ggplot2)
library(plotly)
library(data.table)
library(tidyr)
df = read.csv("Pokemon.csv")
```


## Density charts

```{r, echo=FALSE}
s <-  df %>%
  group_by(Type.1) %>%
  count(name = "freq", sort=TRUE)

s$Type.1 = with(s, reorder(Type.1, freq, desc))
p <- ggplot(s, aes(x = Type.1, y = freq)) +
    geom_point(size=3, color="orange") +
    geom_segment(aes(x=Type.1, xend=Type.1, y = 0, yend=freq))

ggplotly(p)
```

```{r, echo = FALSE}

inputPanel(
  selectInput("name", label = "Choose your pokemon:",
              choices = df$Name, selected = "Bulbasaur"))

renderPlot({
name = as.character(input$name)

row <- df[df$Name == name, ] %>%
  select(Defense, Attack, Sp..Atk, Sp..Def, Speed)
row <- rbind(rep(200, 4), rep(0, 4), row)

radarchart(row, axistype=1, pcol=rgb(0.2,0.5,0.5,0.9) , pfcol=rgb(0.2,0.5,0.5,0.5), plwd=3, cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0, 200, 50), cglwd=0.8)

})


```

```{r, echo = FALSE} 
#sidebarLayout(
  #sidebarPanel,
  #mainPanel,
  #position = c("left", "right"),
  #fluid = TRUE
#)

inputPanel(
  selectizeInput("names", label = "Choose pokemons to compare:", choices = df$Name, selected = NULL, options = list(maxItems = 2, placeholder = "Choose 2 pokemons")))

renderPlot({
name1 = as.character(input$names, 0)
name2 = as.character(input$names, 1)
rows <- df[df$Name %in% c(name1, name2), ] %>%
  select(Name, Defense, Attack, Sp..Atk, Sp..Def, Speed, HP)
rows_t <- transpose(rows[, 2:7])  
colnames(rows_t) <- rows$Name
rows_t$Attribute = colnames(rows)[2:7]

data_long <- gather(rows_t, pokemon, value, name1:name2) %>%
  arrange(factor(Attribute, levels = colnames(rows)[2:7])) %>% 
  mutate(x=factor(Attribute, levels=unique(Attribute)))
  
  ggplot(data_long, aes(x = Attribute, y = ifelse(pokemon == name1, value, -value), fill = pokemon)) +
    geom_bar(stat="identity", position="identity") +
    coord_flip()
})


```



